{% set data = load_setup_py_data() %}  # loads data from the `setup.py` file
{% set version = data.get('version') %}  # get the 'version' from loaded data
{% set summary = data.get('description') %}  # get the 'description' from loaded data
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#loading-data-from-other-files

package:
  name: romicgal
  version: {{ version }}

source:
  path: ../..
#  git_tag: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '0') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - python {{ python }}
    - pip
    - pybind11 >=2.4
    - cgal-cpp ==5.4.1
  host:
    - python {{ python }}
    - pybind11 >=2.4
  run:
    - python {{ python }}
    - cgal-cpp ==5.4.1

test:
  imports:
    - romicgal  # test the import of romicgal
  requires:
    - numpy
    - open3d <0.15
  source_files:
    - sample
    - test
  commands:
    - python test/test.py  # call some wrapped methods but assert (test) nothing

about:
  home: https://docs.romi-project.eu/documentation/
  license: LGPL-3.0
  license_file: LICENSE.txt
  summary: {{ summary }}
  dev_url: https://github.com/romi/romicgal
  doc_source_url: https://github.com/romi/romicgal/blob/master/README.md
