# This workflow will build the Docker image, run python unit tests and integration tests

name: CI

on: pull_request

jobs:
    conda-build:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v2
         - name: Build and upload conda packages
           run: |
            conda build conda/recipe/ -c conda-forge -c open3d-admin --user romi-eu
